name: Java CI/CD Pipeline

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # changed from 'adopt' to 'temurin' as it's more common in documentation

      - name: Build with Maven
        run: mvn -f java-maven-sonar-argocd-helm-k8s/spring-boot-app/pom.xml clean install -DskipTests

      - name: Run Unit Tests with JUnit and Mockito
        run: mvn -f java-maven-sonar-argocd-helm-k8s/spring-boot-app/pom.xml test

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/your-gcp-project-id/my-app:${{ github.sha }} .
          docker push gcr.io/your-gcp-project-id/my-app:${{ github.sha }}
        working-directory: java-maven-sonar-argocd-helm-k8s/spring-boot-app/Dockerfile
      - name: Deploy to Kubernetes using Helm
        run: |
          helm upgrade --install my-app-chart helm/my-app --set image.tag=${{ github.sha }}
